name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^5.1.3
  http: ^0.12.0+2
  font_awesome_flutter: ^8.5.0
  flutter_spinkit: ^4.0.0
  flutter_svg: ^0.14.1
  intl: ^0.16.0
  async_loader: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900
  - family: Chilanka
    fonts:
    - asset: fonts/Chilanka-Regular.ttf
  - family: Julius
    fonts:
    - asset: fonts/JuliusSansOne-Regular.ttf
  - family: DG
    fonts:
    - asset: fonts/DarkerGrotesque-Regular.ttf