name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^5.1.3
  http: ^0.12.0+2
  font_awesome_flutter: ^8.5.0
  flutter_spinkit: ^4.0.0
  flutter_svg: ^0.14.1
  intl: ^0.16.0
  async_loader: ^0.1.2
  flutter_typeahead: ^1.6.1
  connectivity: ^0.4.4
  app_settings: ^1.0.6+2
  modal_progress_hud: ^0.1.3
  animated_text_kit: ^1.3.1
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  image_path: 'images/weatherman.png'
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900
  - family: Chilanka
    fonts:
    - asset: fonts/Chilanka-Regular.ttf
  - family: Julius
    fonts:
    - asset: fonts/JuliusSansOne-Regular.ttf
  - family: DG
    fonts:
    - asset: fonts/DarkerGrotesque-Regular.ttf
  - family: Major Mono
    fonts:
    - asset: fonts/MajorMonoDisplay-Regular.ttf